### ISSUE TITLE
Conclave sample failed build in Mac laptop.

### ISSUE THREAD

**Issue by KztTateyama** [R3Conclave/conclave-samples#42]
Hi,

I tried this Conclave sample.
https://github.com/R3Conclave/conclave-samples/tree/master/conclave-corda-trade
At first, I run below command along the README and failed.
`./gradlew prepareDockerNodes
`
there is a message when I run the command.
```
ktateyam@SR19-023 conclave-corda-trade % ./gradlew prepareDockerNodes                                                          
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :enclave
As Avian has been demised, only GraalVM (graalvm_native_image) is supported and the parameter "runtime" is now deprecated and can be removed.

> Task :enclave:buildUnsignedGraalEnclaveSimulation FAILED
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

FAILURE: Build failed with an exception.

```
I searched `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory` , and It seems to be a mac and docker’s problem.
Also , I found that workaround. if we set a parameter, `platform: linux/x86_64`,  on docker file , we can avoid the problem that I wrote about above.
However, this repository does not contain the docker file.
I guess I can’t set up such a configuration myself because `prepareDockerNodes` wraps it all up.

If anyone has run this sample on a Mac, please let me know how to do so. 

Thank you.

**Comment by snedamle** [comment]
Hi @KztTateyama thanks for raising this, we are looking into this and will get back to you.

**Comment by ashutoshmeher-r3** [comment]
Hi @KztTateyama , This seems to be working fine at our end. Could you please restart docker and try again. Make sure docker is running when you run the prepareDockerNodes  command
